"""remove batch_id and rag_id

Revision ID: e81dbe94c39d
Revises: 09c196ba9090
Create Date: 2026-01-02 19:37:56.199455

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e81dbe94c39d'
down_revision: str | Sequence[str] | None = '09c196ba9090'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('document_batch_id_fkey'), 'document', type_='foreignkey')
    op.drop_column('document', 'batch_id')
    op.drop_column('document', 'rag_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('rag_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('document', sa.Column('batch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('document_batch_id_fkey'), 'document', 'documentbatch', ['batch_id'], ['id'])
    # ### end Alembic commands ###
