"""lifecycle_history

Revision ID: fcb86edb6510
Revises: e81dbe94c39d
Create Date: 2026-01-06 16:24:32.710416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fcb86edb6510'
down_revision: Union[str, Sequence[str], None] = 'e81dbe94c39d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lifecyclehistory', sa.Column('handler_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lifecyclehistory', 'handler_name')
    # ### end Alembic commands ###
