@startuml

package "Data Sources"{
  folder "Github"{

  }
  folder "Gitea"{
    
  }
  folder "Filesystem"{
    
  }
  folder "S3"{
    
  }
  
 
}


package "Sync Agents"{
  Agent "Git"
  Agent "FS"  
  
}
Note left of "Sync Agents"
Agents pull all data and pass to 
ingester for handling
end note

package "Ingester"{
  
  
  Database "doc meta"
  Database "doc contents"
  note top of "doc meta"
  doc meta contains external info that adds context 
  (e.g. author, creation date, etc)
  end note
  package "Haiku Rag"{
    package "Docling"{
      Process parser
      Process chunker
      
    }
    Process embeddings
  }
  storage DocStore {
  Artifact DoclingDocument
  }
  note top of DocStore
  parsed document is stored for future use
  end note

Component router

storage CoreRAG{
  Database CoreLanceDB
}
note left of CoreLanceDB
Core RAG is used to extract doc info such as 
title, location, etc.
end note

Process enricher
note left of enricher
enricher uses CoreRag to add extra meta/context to doc
end note
}
note right of router
Router decides 
which db to use
end note
storage RAG1{
Database LanceDB1
}

[parser]-->[DoclingDocument]
[DoclingDocument]-->chunker
[chunker]-->[embeddings]
[embeddings]-->CoreLanceDB
[CoreRAG]<-->enricher
[enricher]-->[router]
[router]-->[LanceDB1]
[doc meta]-->[enricher]
[Data Sources]-->[Sync Agents]
[Sync Agents]-->[doc contents] 
[Sync Agents]-->[doc meta] 
[doc contents] -->[parser]
[doc meta]-->[router]









@enduml